name: bmi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  audioplayers: ^5.0.0
  fl_chart: ^0.63.0
  flutter_charts: ^0.5.1
  syncfusion_flutter_charts: ^23.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/

